### ISSUE TITLE
This used to work on all platforms(Android/iOS/Windows) but doesn't work on Windows anymore

### ISSUE THREAD

**Issue by opmaaadi** [haohaolee/shadowsocks-v2ray-tls-ws#2]
I created a VPN server using your excellent script and it worked perfectly on Android, iOS and Windows.

After a month or so, my server stopped working on Windows but continues to work on Android and iOS. The same thing happened to one my friends who was also using this server.

There's nothing off in the logs too.
```
=========================
Registered Encryptor Info
aes-128-gcm=>AEADOpenSSLEncryptor
aes-192-gcm=>AEADOpenSSLEncryptor
aes-256-gcm=>AEADOpenSSLEncryptor
chacha20-ietf-poly1305=>AEADOpenSSLEncryptor
xchacha20-ietf-poly1305=>AEADSodiumEncryptor
plain=>PlainEncryptor
none=>PlainEncryptor
=========================

2022-11-08 00:56:12.0464|DEBUG|Shadowsocks.Util.Utils|Cannot get Windows 10 system theme mode, return default value 0 (dark mode).
2022-11-08 00:56:12.1998|DEBUG|Shadowsocks.Controller.TCPHandler|connect to gateway-us-east1-d.discord.gg:443
2022-11-08 00:56:12.1998|DEBUG|Shadowsocks.Controller.TCPHandler|connect to gateway-us-east1-d.discord.gg:443
2022-11-08 00:56:12.1998|DEBUG|Shadowsocks.Controller.TCPHandler|connect to mtalk.google.com:5228
2022-11-08 00:56:12.1998|DEBUG|Shadowsocks.Controller.TCPHandler|Socket connected to ss server: My_Profile_Name (mydomain.com:443)
```

Here's also v2ray plugin's logs: (again nothing strange)

```
2022/11/08 01:01:52 V2Ray 4.38.3 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.16.15 windows/386)
2022/11/08 01:01:52 A unified platform for anti-censorship.
2022/11/08 01:01:52 [Warning] V2Ray 4.38.3 started
2022/11/08 01:01:53 127.0.0.1:2410 accepted tcp:127.0.0.1:0
2022/11/08 01:01:53 127.0.0.1:2412 accepted tcp:127.0.0.1:0
2022/11/08 01:01:53 127.0.0.1:2413 accepted tcp:127.0.0.1:0
```

Shadowsocks + V2ray (without TLS) works fine though.

I've tested a few more servers from different providers and none of them works on Windows for me. (All of them with one domain and its subdomains though)

**Comment by opmaaadi** [comment]
@Arman92 I'd appreciate if you could help in case it's something Iran specific.

**Comment by Arman92** [comment]
> @Arman92 I'd appreciate if you could help in case it's something Iran specific.

@opmaaadi If you're using cloud flare DNS proxy, it's possible that I.R is blocking cloudflare IPs. 

You could further check this if you can reach your server by using a websocket test tool:
https://www.piesocket.com/websocket-tester

`wss://yourdomain.com/v2ray`
Note: `/v2ray` should match [URL_PATH](https://github.com/haohaolee/shadowsocks-v2ray-tls-ws/blob/master/scripts/start-server.sh#L7) in your environment variables (if you have changed it)

However I would suggest changing the path to something random.

Are all your clients on the same WiFi network? I've heard on some ISPs Shadowsocks+WS does not work (mostly because of CloudFlare being blocked)

**Comment by opmaaadi** [comment]
> > @Arman92 I'd appreciate if you could help in case it's something Iran specific.
> 
> @opmaaadi If you're using cloud flare DNS proxy, it's possible that I.R is blocking cloudflare IPs.
> 
> You could further check this if you can reach your server by using a websocket test tool: https://www.piesocket.com/websocket-tester
> 
> `wss://yourdomain.com/v2ray` Note: `/v2ray` should match [URL_PATH](https://github.com/haohaolee/shadowsocks-v2ray-tls-ws/blob/master/scripts/start-server.sh#L7) in your environment variables (if you have changed it)
> 
> However I would suggest changing the path to something random.
> 
> Are all your clients on the same WiFi network? I've heard on some ISPs Shadowsocks+WS does not work (mostly because of CloudFlare being blocked)

This is driving me crazy honestly.

1- I checked different ISPs. No difference. Works on Android and iOS but not on Windows.
2- Changed the URL_PATH to `/index`. No difference.
3- Checked the server on `PiesSocket`, connection is successfully established.
4- Used ArvanCloud name servers instead of Cloudflare's. Again no difference.
5- There's also another public server ([here](https://t.me/internet4iran/175)) which also doesn't work on my windows machine. It does work on Android, albeit a bit slow due to being public.

I suspect it could be due to the TLS certificate being not valid in the eyes of Windows.

```
acme.sh  --register-account  -m mypersonalsecureemail@proton.me --server zerossl


acme.sh --issue -d "$DOMAIN" --standalone --keylength ec-256 --reloadcmd "$RELOADCMD" \
      --key-file "$KEY_PATH" --fullchain-file "$CERT_PATH"
```

How does ZeroSSL confirm here that the person running this script is the owner of the domain? I onced generated a TLS certificate in the ZeroSSL website and verification was needed (either you have a email address on that domain or set DNS (CNAME))

I could send you my server config so you could check it for yourself.

Thanks!

**Comment by Arman92** [comment]
Did you check if you can reach your server in web socket test tool? https://www.piesocket.com/websocket-tester

ZeroSSL/Let'sEncrypt use acme challenges to prove you are the owner of the domain, read more here:
https://letsencrypt.org/docs/challenge-types/

` acme.sh` implements those challenges so you can easily obtain a certificate.

**Comment by opmaaadi** [comment]
> Did you check if you can reach your server in web socket test tool? https://www.piesocket.com/websocket-tester
> 
> ZeroSSL/Let'sEncrypt use acme challenges to prove you are the owner of the domain, read more here: https://letsencrypt.org/docs/challenge-types/
> 
> ` acme.sh` implements those challenges so you can easily obtain a certificate.

I'd made a silly mistake. I was using the x86 version of V2Ray plugin!

The strange thing is, the x86 version was working for 10 days for me and a buddy of mine and suddenly stopped working when using TLS for both of us!

Thank you so much Arman!
